#General
seed: 42

#Dataset
samples_per_epoch_train: 10000
samples_per_epoch_test: 10000
max_epochs: 10


#Language
msg_len: 5
n_symbols: 5

# Pretraining
pretrain: "shapes"
pretrain_n_epochs: 1


#Training settings
learning_rate: 0.001
batch_size: 128

# Sender params:
fixed_size: False


# Predictor settings
predictor_loss_weight: 0



