
#Dataset
samples_per_epoch_train: 10000
samples_per_epoch_test: 1000
max_epochs: 10
n_receiver: 3
n_attributes: 5
attributes_size: 5
#Language
msg_len: 10
n_symbols: 250


pretrain_n_epochs: 5


#Grid search settings

n_runs: 1
grid_search_vars: ["learning_rates", "batch_sizes", "predictor_loss_weights"]

metric: 'val_accuracy_epoch'

#Training settings
learning_rates: [  0.005, 0.001, 0.0001]
batch_sizes: [32, 128, 512]

with_predictor: True

# Sender params:
fixed_size: False
n_remove_classes: 0

# Predictor settings
predictor_loss_weights: [0.0001]
hidden_size_predictor: 128







