
#Dataset
samples_per_epoch_train: 10000
samples_per_epoch_test: 10000
max_epochs: 15
n_receiver: 3
n_attributes: 2
attributes_size: 2
#Language
msg_len: 10
n_symbols: 25


pretrain_n_epochs: 5


#Grid search settings

n_runs: 1
grid_search_vars: ["learning_rates", "batch_sizes"]



#Training settings
learning_rates: [  0.01, 0.005, 0.001]
batch_sizes: [32, 128, 512]

with_predictor: False

# Sender params:
fixed_size: False


# Predictor settings
predictor_loss_weights: [0.1, 0.001, 0.0001]
hidden_size_predictor: 128







